### ISSUE TITLE
Intermittent Null Initiative in Combat

### ISSUE THREAD

**Issue by Xervous** [Zgrill2/ShimmeringReach-FVTT#33]
Sometimes when initiative is rerolled for a new round one or more combatants fail to have their initiative written.

In this case the roll is still being performed for the actor, its result is processed into the message that is displayed in chat, the initiative value is put into the array that is passed as a parameter for the `updateEmbeddedDocuments()` call as part of `rollInitiative()`. Usually the combatant will have the rolled initiative replace the `null` initiative value that it begins with at the start of a new round, but either it's failing to write or something else is writing a `null` over the value.

Call structuring for proceeding to next round

`resetAll()`: nulls initiative and zeroes order.  
`rollAll()`: calls `rollInitiative()` for all combatants who the client has permission to roll, and only ones that have `null` initiative. This consistently recognizes all combatants have `null` initiative from `resetAll()` and passes all combatant IDs to `rollInitiative()`
> `rollInitiative()`: line 195 console log of `updates` demonstrates that all ID and initiative pairings are present in the array being passed to `updateEmbeddedDocuments()`. Line 196 messy console log shows that all initiatives before update are currently `null`, as expected. Line 203 console log shows initiatives that have been successfully written to the combatants. In the event of the bug the line 203 console log will return a `null` instead of the number that was logged from line 195 AND the roll result displayed in chat.

`assignOrder()`: locks turn order to allow for initiative manipulation. Fully functional 

Unless some other place is asynchronously nulling initiative for actors due to race conditions it looks like the issue is tied up in `updateEmbeddedDocuments()`.

**Comment by Zgrill2** [comment]
Can not reproduce.  I get the opposite behavior, line 197 is null, line 203 displays expected number. 
![image](https://user-images.githubusercontent.com/9122236/140651847-37a24412-a8d2-4982-bac4-01774aa69de8.png)

In the future, it is recommended to use break points instead of console.logs as objects printed in console logs are "lazy loaded" meaning what is printed does not reflect what the object looked like at the time of the console.log call but rather the object at some point in the future from that point.

**Comment by Xervous** [comment]
Resolved
